crt: Add a missing declaration for __intrinsic_setjmpex
This fixes the following warning:

    ../misc/arm64ec/setjmp.c:87:28: error: no previous prototype for function '__intrinsic_setjmpex' [-Werror,-Wmissing-prototypes]
      GEN      libarm64/gcrt1.o
       87 | int __attribute__((naked)) __intrinsic_setjmpex( jmp_buf buf, void *frame )
          |                            ^
    ../misc/arm64ec/setjmp.c:87:1: note: declare 'static' if the function is not intended to be used outside of this translation unit
       87 | int __attribute__((naked)) __intrinsic_setjmpex( jmp_buf buf, void *frame )
          | ^
          | static